$(document).ready(function() {

  var trait = new Array(
    "Grouchy", 
    "Jolly", 
    "Brave", 
    "Clever",
    "Bombastic",
    "Aging",
    "Youthful",
    "Prickly",
    "Loner",
    "Life-of-the-party",
    "Lazy",
    "Nasty",
    "Arrogant",
    "Helpful",
    "Slick",
    "Serious",
    "Stuck-up",
    "Affable",
    "Bossy",
    "Secretly insecure",
    "Bold and brash",
    "Risk-taking",
    "Vain",
    "Eccentric",
    "Funny",
    "Passionate",
    "Ambitious",
    "Debonair",
    "Bungling",
    "Savage",
    "Carefree",
    "Excitable",
    "Intense",
    "Accident-prone",
    "Gregarious",
    "Insufferable",
    "Too-gay-to-function",
    "Flirty",
    "Fastidious",
    "Obnoxious",
    "Hard-working",
    "Walking disaster",
    "Youthful",
    "Aloof",
    "Coy",
    "Adreneline junkie",
    "Scatter-brained",
    "Proud",
    "Pessimistic",
    "Self-centered",
    "Jealous",
    "Warm-hearted",
    "Brutally honest",
    "Fair-minded",
    "Perpetually jumpy",
    "Insufferably kind",
    "Earnest",
    "Disciplined",
    "Grizzled veteran",
    "Absolutely insane",
    "Shaky",
    "Nurturing",
    "Pushover",
    "Good and pure",
    "Chaotic",
    "Stuff-shirt",
    "Adorable",
    "Melancholy",
    "Resiliant",
    "Haunted",
    "Eager",
    "Snarky",
    "Vivacious",
    "Dimwit",
    "Genius",
    "Exceptionally talented",
    "Laidback",
    "Hopeless romantic",
    "Bookish",
    "Artistic",
    "Jaded",
    "Unsettlingly handsome",
    "Loud mouth",
    "Finely-aged",
    "Uncomfortbly attractive",
    "Anti-social",
    "Super buff",
    "Curious",
    "Hand-wringing",
    "Hospitable",
    "Absolute basard",
    "Southern belle",
    "Well-meaning",
    "Wolfish",
    "Street-smart",
  );

  var quality = new Array(
    " ",
    " ",
    " ",
    " ",
    " ",
    "lesbian",
    "pansexual",
    "bisexual",
    "transgender",
    "asexual",
    "non-binary",
    "gay",
    "queer",
    "feminine",
    "masculine",
  );

  var species = new Array (
    "Alpha Centaurian",
    "Anabaj",
    "Andorian",
    "Android",
    "Argellian",
    "Arkarian",
    "Bajoran",
    "Ba'ku",
    "Betazoid",
    "Bolian",
    "Breen",
    "Brikarian",
    "Caitian",
    "Caldonian",
    "Cardassian",
    "Deltan",
    "El-Aurian",
    "Ferengi",
    "Gideon",
    "human",
    "Karjurian",
    "Kelpian",
    "Klingon",
    "Na'kuhl",
    "Orion",
    "Orion/Andorian"
    "Risian",
    "Romulan",
    "Sivaoan",
    "Talorian",
    "Trill",
    "Vulcan",
    "Xindi Insectoid",
  );

  var job = new Array(
    "security officer", 
    "scientist", 
    "operations officer", 
    "engineer",
    "transporter tech",
    "first officer",
    "pilot",
    "intelligence officer",
    "starship captain",
    "space station commander",
    "counselor",
    "warp engineer",
    "inventor",
    "lagabout",
    "self-styled warrior",
    "professional athlete",
    "linguist",
    "therapist",
    "doctor",
    "nurse",
    "space-farer",
    "merchant",
    "chef",
    "scavenger",
    "parent of three",
    "single parent",
    "lighthouse keeper",
    "prosthetics maker",
    "serial monogamist",
    "match-maker",
    "former Maquis",
    "beaurocrat",
    "phaser-maker",
    "lawyer",
    "astronomer",
    "fiction writer",
    "librarian",
    "fraud",
    "smuggler",
    "healer",
    "Trill symbiot expert",
    "bounty hunter",
    "diplomat",
    "model",
    "spaceship designer",
    "club promoter",
    "historian",
    "food writer",
    "fashion designer",
    "tinkerer",
    "actor",
    "journalist",
    "cook",
    "translator",
    "alien culture consultant",
    "botanist",
    "painter",
    "bartender",
    "photographer",
    "xenobiologist",
    "musician",
    "town gossip",
    "village idiot",
    "tea house owner",
    "teacher",
    "space-taxi driver",
    "farmer",
    "grocer",
    "university student",
    "terrorist",
    "drugs dealer",
    "mechanic",
    "author",
    "travel writer",
    "confectioner",
    "retired Starfleet",
    "hacker",
    "computer expert",
    "monk",
    "kid",
  );
  
  var fact = new Array(
    "can't seem to shut up", 
    "has vivid visions", 
    "can use magic but doesn't",
    "has a secret criminal life",
    "is always hinting at a dark past",
    "can barely use a tricorder",
    "had an accident with transporter",
    "was struck by lightning",
    "has a secret ambition",
    "is preoccupied with vulcans",
    "keeps a strange pet",
    "is a gambling genius",
    "is a failed scientist",
    "believes they were famous in a past life",
    "is haunted by a ghost",
    "is obsessed with death",
    "talks to space ships",
    "refers to themselves in the third person",
    "started their own business",
    "was raised by plants",
    "who has a penchant for the dramatic",
    "is estranged from their family",
    "is always talking about their novel",
    "loves dispensing wisdom",
    "can't remember childhood",
    "walks with a limp",
    "wears too much jewelry",
    "claims to be related to Will Riker",
    "has managed to make a wormhole",
    "regrets literally everything",
    "has many acquaintences but no true friends",
    "learned why it's bad to meet your hero",
    "had a near death experience",
    "breaks into song at the drop of a hat",
    "is always falling in love",
    "hates their father",
    "has a proper fan club",
    "is afraid of transporters",
    "plays in a band",
    "parties like there's no tomorrow",
    "is a tea connosieur",
    "is covered in floral tattoos",
    "is about as deadly as a cranberry muffin",
    "has never minded their own business in their life",
    "always seems tired",
    "wears sunglasses indoors",
    "will try to murder you",
    "often wears mesh shirts",
    "is chasing some kind of meaning in life",
    "is known for absolutely garish sweaters",
    "has a false eye",
    "will never go back home",
    "is always up for a drink",
    "dreams of being famous",
    "bartered away something important",
    "runs a home for orphans",
    "spends every day atoning for a past wrong",
    "is searching for their family",
    "almost married their sibling",
    "is keenly interested in soil",
    "thinks a little pain never hurt anyone",
    "cares for stray animals",
    "has a great garden",
    "teaches kids' warp core repair their free time",
    "time-travelled accidentally",
    "can speak Vulcan",
    "saw a horrible murder",
    "basically raised their siblings",
    "tutors Bajoran",
    "likes crossword puzzles",
    "is really good at chess",
    "is kind of a stalker",
    "is super annoyed by human culture",
    "eats gagh every day for breakfast",
    "brings baked goods to every gathering",
    "confused by own popularity",
    "is reluctantly helpful",
    "is anthropoligically interested in others' gossip",
    "is single-handedly holding this shit together",
    "has a difficult relationship with their mother",
    "has a reputation for being overly affectionate",
    "enjoys being angry",
    "is obsessed with pizza",
    "was a child prodigy",
    "is known as a washed-up has-been",
  );
  
  randomTrait = trait[Math.floor( Math.random() * trait.length)];
  randomQuality = quality[Math.floor( Math.random() * quality.length)];
  randomSpecies = species[Math.floor( Math.random() * species.length)];
  randomJob = job[Math.floor( Math.random() * job.length)];
  randomFact = fact[Math.floor( Math.random() * fact.length)];
  
  $('#trait').text(randomTrait);
  $('#quality').text(randomQuality);
  $('#species').text(randomSpecies);
  $('#job').text(randomJob);
  $('#fact').text(randomFact);

  $('#trait').click(function() {
    randomTrait = trait[Math.floor( Math.random() * trait.length)];
    $('#trait').text(randomTrait);
  });
  $('#quality').click(function() {
    randomQuality = quality[Math.floor( Math.random() * quality.length)];
    $('#quality').text(randomQuality);
  });
  $('#species').click(function() {
    randomSpecies = species[Math.floor( Math.random() * species.length)];
    $('#species').text(randomSpecies);
  });
  $('#job').click(function() {
    randomJob = job[Math.floor( Math.random() * job.length)];
    $('#job').text(randomJob);
  });
  $('#fact').click(function() {
    randomFact = fact[Math.floor( Math.random() * fact.length)];
    $('#fact').text(randomFact);
  });

  $("#refresh").click(function(){
    location.reload(true);
  });
  
})
